env:
  CIRRUS_CLONE_DEPTH: 1

container:
  image: python:slim

test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt
  test_script: pytest
  always:
    junit_artifacts:
      path: "*.xml"
      type: text/xml
      format: junit
