version: 2
jobs:
  build:
    working_directory: ~/sample-python-app
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r requirements.txt
            pytest
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml
          destination: tr1
